const maintenanceSection=document.createElement('section');
maintenanceSection.id='maintenance';maintenanceSection.className='hidden';
maintenanceSection.innerHTML=`<div class="card"><h2>Bromine Feeder & Filter Care</h2><p><b>Bromine tablets: replenish about weekly.</b> Check the supply and test bromine regularly; do not wait until the feeder is empty.</p><p><b>Filter: clean about monthly</b>, or sooner when pressure rises <b>8–10 PSI above the clean-filter starting pressure</b>, unless the filter instructions specify another threshold.</p><p>These are average service intervals. Bather load, water temperature, operating hours, debris and water conditions can change how often service is needed.</p></div>
<div class="card"><h3>When to clean the filter</h3><p>Record the pressure after cleaning and fully bleeding the filter, with normal circulation running. Compare future readings at the same pump speed and valve settings.</p><p><b>Example:</b> clean-filter starting pressure 10 PSI → cleaning range 18–20 PSI. This is a rise above the starting reading, not a universal pressure limit. Do not exceed the equipment pressure rating or ignore reduced flow.</p></div>
<div class="card"><h3>Before opening equipment</h3><p>Keep bathers out during service. Turn the system off and disable automatic restart. Follow the installed equipment's pressure-release procedure. Before opening a filter lid or clamp, stand clear, release pressure through the air-relief valve and verify the gauge reads zero. Never loosen a lid to release pressure.</p></div>
<div class="card"><h3>Filter cleaning — choose the plumbing arrangement</h3><p>These steps cover cartridge filters. Use the procedure matching the installed plumbing, including on custom-named pools.</p>
<details><summary>Freestanding: RISE, XLR8, THRIVE, ECO / EVO</summary><ol><li><b>RISE only:</b> equalize the water using the unit's normal equalization procedure, then switch the system off. <b>XLR8, THRIVE, ECO and EVO:</b> switch the system off; no water-level equalization is needed. Prevent automatic restart on every system.</li><li>Open the filter bleeder/air-relief valve to release pressure and allow the filter to drain through its intended drain path. Verify zero pressure before opening.</li><li>Open the lid using the filter's prescribed release procedure. Remove the cartridge. Rinse between the pleats with a garden hose; use a compatible cartridge cleaner as directed for oils or scale. Replace damaged or worn cartridges.</li><li>Install the cleaned or replacement cartridge. Clean and inspect the lid seal, then secure the lid and clamp exactly as required for that filter.</li><li>Close the bleeder during reassembly if required by the unit procedure. Before restart, position the air-relief valve as the installed filter manual requires; many Pentair filters require it open before the pump starts.</li><li>Restart using the air-bleeding steps below. Record the clean-filter pressure.</li></ol></details>
<details><summary>200, 300, 350, 750, 1200, 2000, 3500, PLUNGE 7&#39;9&quot;, PLUNGE 14&#39; — inlet/outlet isolation valves</summary><ol><li>Switch the system off and prevent automatic restart. Close the filter inlet and outlet isolation valves.</li><li>Open the drain and air-relief valves as required to release pressure and drain the filter. Verify zero pressure before opening the lid.</li><li>Remove and clean the cartridge as described above, or replace it if damaged. Reinstall it and secure the seal, lid and clamp according to the filter instructions.</li><li>Close the drain. Restore both inlet and outlet valves to their normal operating positions before restarting; never run the pump against closed isolation valves.</li><li>Position the air-relief valve for startup according to the filter manual, then restart and bleed the air as described below.</li></ol></details>
<h3>Bleeding air from the filter</h3><p>With the lid and clamp fully secured, stand clear of the filter during restart. Use the designated bleeder/air-relief valve to let trapped air escape. For Pentair filters requiring an open relief valve at startup, open it before turning the pump on. Once a steady stream of water comes out, close the valve only enough to stop the flow. <b>Do not overtighten.</b></p><p>If air keeps returning, water does not appear, or there is a leak, stop the system and have the cause checked before restarting. Do not keep loosening the lid or clamp.</p></div>
<div class="card"><h3>Replenishing 1-inch bromine tablets</h3><p><b>RISE, ECO and EVO: CMP PowerClean Mini feeder.</b> Other systems commonly use the Pentair 320; verify the model installed on the pool.</p><p>Use only clean, slow-dissolving 1-inch bromine tablets approved for the feeder. Keep shock, other chemicals and different tablet types out of the bromine feeder. Wear the protection specified on the chemical label and avoid breathing fumes.</p><ol><li>Note the normal dial setting. Turn the system off, prevent automatic restart, and set the feeder dial to <b>0 / closed</b>.</li><li>Allow the feeder to drain and relieve pressure using its installed procedure. Both the CMP PowerClean Mini and Pentair 320 recharge instructions include a one-minute wait. Below-water-level installations need their drain/isolation procedure before opening.</li><li>Only after pressure is relieved, remove the lid and replenish tablets without exceeding the feeder capacity.</li><li>Inspect and clean the lid seal. Refit the lid and hand-tighten as specified. <b>Secure the lid before reopening the dial or restarting the pump.</b></li><li>Restore circulation and the normal dial setting according to the installed procedure. Confirm feeder flow and check for leaks. Retest bromine and adjust the feed setting as needed.</li></ol><h4>Avoiding an air lock</h4><p>Filling and priming depend on the plumbing. Use the unit-specific priming procedure. If pump flow is needed to fill the feeder, the lid must be secured before starting. Stop and depressurize again before any further lid access.</p><details><summary>Pentair 320 only — water level when stopped</summary><p>The Pentair 320 can lower its water level when the pump stops; visible air alone does not prove an air lock. This note does not describe the CMP PowerClean Mini installed on RISE, ECO and EVO.</p></details><p>If bromine stays low despite tablets and normal circulation, have the flow, dial, tubing and check valve checked before further adjustment. Do not run with the cap loose to force air out.</p></div>`;
document.querySelector('main').appendChild(maintenanceSection);
function maintenanceButton(){const b=document.createElement('button');b.className='secondary';b.textContent='Bromine Feeder & Filter Care';b.onclick=()=>show('maintenance');return b}
$('home').appendChild(maintenanceButton());
const maintenanceReference=document.createElement('div');maintenanceReference.className='card';maintenanceReference.appendChild(maintenanceButton());$('ref').appendChild(maintenanceReference);
const renderLogBeforeMaintenance=renderLog;renderLog=function(type){renderLogBeforeMaintenance(type);if(type==='weekly')$('logForm').prepend(maintenanceButton())};
